os: linux
sudo: false
language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - nightly
  - pypy3

env:
  - TOXENV=py

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.3
    - python: nightly
    - python: pypy3
  fast_finish: true

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coveralls
  - coverage combine
  - coverage report
  - coveralls

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
